spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost/yuyue?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 10 #最大连接数
        max-idle: 10   #最大等待连接中的数量
        min-idle: 1     #最小等待连接中的数量
        #定时任务，检查连接池中的连接是否满足至少有 min-idle 的个数，同时，不超过 max-idle 那么多个数
        time-between-eviction-runs: 10s

server:
  port: 80
mybatis-plus:
  configuration:
    #日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰命名
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      table-prefix: t_   #表前缀
      id-type: auto
#短信配置
AccessKey-ID: "LTAI5tNUSw7bgpkaRvmrx4FK"
AccessKey-Secret: "sS2jwiRqxX4dnIKicEoXSi5Hg24ewg"
SysRegionId: "cn-hangzhou"
SignName: "阿里云短信测试"
TemplateCode: "SMS_154950909"
#七牛云存储配置
AccessKey: "LpA7nTa8DFRfhZlGnxGH2XDeEDkpvH3e1I_lwMvq"
SecretKey: "o-n-p9g4SXuZFq4fzdtXxOIcXye_wnVJswNTAAdP"
Bucket: "itheima-heathy"
MemoryArea: "z2"  #华东 z0 华北  z1 华南 z2 北美 na0 东南亚 as0
############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false